stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8"

before_script:
  - pod deintegrate
  - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace Getfit.xcworkspace -scheme Getfit | xcpretty
    - xcodebuild test -workspace Getfit.xcworkspace -scheme Getfit -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' | xcpretty -s
  tags:
    - Getfit

